#include <iostream>
#include <string.h>
#include <stdio.h>
#include <numeric>
#include <thread>
#include <set>

#include <libOTe/config.h>
#include <cryptoTools/Crypto/PRNG.h>
#include "libOTe/Vole/Silent/SilentVoleReceiver.h"
#include "libOTe/Vole/Silent/SilentVoleSender.h"
#include "libOTe/TwoChooseOne/OTExtInterface.h"
#include "libOTe/Base/SimplestOT.h"

#include "../smallSetVoleFast.h"   // SmallSetVoleSender25519 / Receiver
#include "../ZKP.h"               // PROPRF_ZKProver / PROPRF_ZKVerifier
#include "../field25519/fe25519.h"
#include "../fast_residue_25519.h" // for utility functions (random_fe25519 etc.)

using namespace osuCrypto;
using namespace std;

int main() {

    // ------------------ Protocol parameters ------------------
    const int leval = 10;                      // number of v (as in OPRF)
    const int lcom  = 61;                     // length of offset/com domain
    const int k     = 53;                       // number of challenge bits
    const int small_set_bits = 8;
    const int statistical_security_bits = 64;
    const int N = 1 << small_set_bits;         // 256

    // Instantiate prover / verifier
    PROPRF_ZKProver prover(leval, lcom, k, small_set_bits, statistical_security_bits);
    PROPRF_ZKVerifier verifier(leval, lcom, k, small_set_bits, statistical_security_bits);

    // ------------------ Public offsets (same as in OPRF) ------------------
    std::vector<fe25519> offsets(leval + lcom);
    {
        PRNG offsetPrng(block(0, 0));          // deterministic
        for (size_t i = 0; i < offsets.size(); ++i) {
            do {
                random_fe25519(&offsets[i], offsetPrng);
                // ensure no collision (simple check for test)
                bool collision = false;
                for (size_t j = 0; j < i; ++j)
                    if (offsets[i] == offsets[j]) { collision = true; break; }
                if (!collision) break;
            } while (true);
        }
    }

    // ------------------ Build a valid witness ------------------
    std::vector<fe25519> w(79);
    PRNG prng(block(123456789, 987654321));    // fixed seed for reproducibility

    // K
    random_fe25519(&w[K_pos], prng);

    // a_witness (rename to avoid conflict with PPRF 'a')
    fe25519 a_witness;
    random_fe25519(&a_witness, prng);
    // y_0 = a_witness
    std::vector<fe25519> y(9);
    y[0] = a_witness;
    for (size_t i = 1; i <= 8; ++i) {
        fe25519 temp = y[i-1];
        fe25519 y2 = temp * temp;
        fe25519 y4 = y2 * y2;
        y[i] = y4 * temp;        // y_i = y_{i-1}^5
    }

    // a0 = y8^2 * y4 * y1^2
    fe25519 y8sq = y[8] * y[8];
    fe25519 y1sq = y[1] * y[1];
    fe25519 a0 = y8sq * y[4] * y1sq;

    // a1 from constraint 67: y1 * a0 = y0^2 * y3 * a1
    fe25519 y0sq = y[0] * y[0];
    fe25519 right_inv = y0sq * y[3];
    fe25519_invert(&right_inv, &right_inv);
    fe25519 a1 = (y[1] * a0) * right_inv;  // uses fe25519 division (inverse)

    // Compute c0 = 1/(y0 * a1)  (so that c0 * c1 * y0 * a1 = 1 with c1 = 1)
    fe25519 c0, temp;
    temp = y[0] * a1;
    fe25519_invert(&c0, &temp);
    fe25519 c1;
    fe25519_setone(&c1);

    // v_i: product of first 5 is c0, product of last 5 is c1
    std::vector<fe25519> v(leval);
    v[0] = c0;                    // product of first five = c0
    for (int i = 1; i < 5; ++i)   fe25519_setone(&v[i]);
    for (int i = 5; i < 10; ++i)  fe25519_setone(&v[i]);

    // b_i (random non‑zero)
    std::vector<fe25519> b(k);
    for (auto &bi : b) random_fe25519(&bi, prng);

    // ru, rv (random)
    fe25519 ru, rv;
    random_fe25519(&ru, prng);
    random_fe25519(&rv, prng);

    // u_i = (K + offsets[i]) * v_i
    std::vector<fe25519> u(leval);
    for (size_t i = 0; i < leval; ++i) {
        u[i] = (w[K_pos] + offsets[i]) * v[i];
    }

    // gamma (random, as would be generated by VOLE+)
    std::vector<fe25519> gamma(leval);
    for (auto &g : gamma) random_fe25519(&g, prng);

    // cu, cv
    fe25519 cu = ru, cv = rv;
    for (size_t i = 0; i < leval; ++i) {
        cu += gamma[i] * u[i];
        cv += gamma[i] * v[i];
    }

    // challenge c (distinct indices)
    std::vector<unsigned char> c_vec(k);
    {
        std::set<int> used;
        while (used.size() < (size_t)k) {
            int idx = prng.get<uint32_t>() % lcom;
            if (used.insert(idx).second)
                c_vec[used.size()-1] = static_cast<unsigned char>(idx);
        }
    }

    // m_i = b_i * (K + offsets[leval + c_vec[i]])
    std::vector<fe25519> m(k);
    for (size_t i = 0; i < k; ++i) {
        fe25519 lci = offsets[leval + c_vec[i]];
        m[i] = b[i] * (w[K_pos] + lci);
    }

    // Assemble witness vector w (size 79)
    w[K_pos] = w[0];  // already set
    for (size_t i = 0; i < leval; ++i) w[v_offset + i] = v[i];
    for (size_t i = 0; i < k; ++i) w[b_offset + i] = b[i];
    for (size_t i = b_offset + k; i < 64; ++i) w[i].setzero();
    w[ru_pos] = ru;
    w[rv_pos] = rv;
    for (size_t i = 0; i <= 8; ++i) w[y_offset + i] = y[i];
    w[a0_pos] = a0;
    w[a1_pos] = a1;
    w[c0_pos] = c0;
    w[c1_pos] = c1;



    // ------------------ Networking & Small‑set VOLE setup ------------------

    auto sockets = coproto::LocalAsyncSocket::makePair();
    int vole_len = prover.vole_len;   
    int k_vole   = prover.k_vole;     

    // Prover thread (acts as sender in the small‑set VOLE)
    std::thread proverThread([&]() {
        PRNG prngProver(sysRandomSeed());

        // Base OT
        SimplestOT otSender;
        int baseCount = RegularPprfSender<block,CTX>(N, k_vole).baseOtCount();
        std::vector<std::array<block,2>> sendOTs(baseCount);
        auto baseProto = otSender.send(sendOTs, prngProver, sockets[0]);
        coproto::sync_wait(macoro::wrap(baseProto));

        // PPRF sender
        RegularPprfSender<block,CTX> pprfSend(N, k_vole);
        pprfSend.setBase(sendOTs);
        Vec b_ot(N * k_vole);
        coproto::sync_wait(macoro::wrap(
            pprfSend.expand(sockets[0], 0, prngProver.get(), b_ot, FORMAT, false, 1)));


        // Small‑set VOLE sender
        SmallSetVoleSender25519 ssvSend(vole_len, small_set_bits, k_vole);
        std::vector<std::vector<fe25519>> ui, vi;
        auto ssvProto = ssvSend.send(ui, vi, b_ot, 0, prngProver, sockets[0]);
        coproto::sync_wait(macoro::wrap(ssvProto));


        // Commit witness
        auto commitProto = prover.commit_to_witness(w, ui, vi, prngProver, sockets[0]);
        coproto::sync_wait(commitProto);


        // Prove
        auto proveProto = prover.prove(gamma, m, cu, cv, offsets, c_vec, prngProver, sockets[0]);
        coproto::sync_wait(proveProto);
    });

    
    // Verifier side (main thread)
    PRNG prngVer(sysRandomSeed());

    // Base OT
    SimplestOT otReceiver;
    RegularPprfReceiver<block,CTX> pprfRecv;
    pprfRecv.configure(N, k_vole);                  // configure first

    int baseCount = pprfRecv.baseOtCount();
    std::vector<block> recvOTs(baseCount);
    BitVector recvBits = pprfRecv.sampleChoiceBits(prngVer);
    auto baseProto = otReceiver.receive(recvBits, recvOTs, prngVer, sockets[1]);
    coproto::sync_wait(macoro::wrap(baseProto));

    // PPRF expansion
    pprfRecv.setBase(recvOTs);
    Vec pprfOutput(N * k_vole);
    std::vector<u64> points(k_vole);
    pprfRecv.getPoints(points, FORMAT);
    coproto::sync_wait(macoro::wrap(pprfRecv.expand(sockets[1], pprfOutput, FORMAT, false, 1)));


    // Small‑set VOLE receiver
    SmallSetVoleReceiver25519 ssvRecv(vole_len, small_set_bits, k_vole);
    std::vector<std::vector<fe25519>> oi;
    std::vector<fe25519> hi;
    auto ssvProto = ssvRecv.receive(oi, hi, pprfOutput, 0, points, prngVer, sockets[1]);
    coproto::sync_wait(macoro::wrap(ssvProto));

    // Commit witness (verifier)

    bool good = false;
    auto commitProtoVer = verifier.commit_to_witness(good, oi, hi, prngVer, sockets[1]);
    coproto::sync_wait(commitProtoVer);
    if (!good) {
        std::cerr << "VOLE consistency check failed" << std::endl;
        proverThread.join();
        return 1;
    }

    // Verify
    bool valid = false;
    auto verifyProto = verifier.verify(valid, gamma, m, cu, cv, offsets, c_vec, prngVer, sockets[1]);
    coproto::sync_wait(verifyProto);

    proverThread.join();

    std::cout << "ZKP verification " << (valid ? "PASSED" : "FAILED") << std::endl;
    std::cout << "Correct: " << std::boolalpha << valid << std::endl;
    return valid ? 0 : 1;
}